print("***********************")
print("โปรเเกรมหยิบสินค้าใส่ตระกร้า")
print("***********************")
basket=[]
Products1 = input("หยิบสินค้าชิ้นที่ 1 :")
basket.append(Products1)
Products2 = input("หยิบสินค้าชิ้นที่ 2 :")
basket.append(Products2)
Products3 = input("หยิบสินค้าชิ้นที่ 3 :")
basket.append(Products3)
Products4 = input("หยิบสินค้าชิ้นที่ 4 :")
basket.append(Products4)
Products5 = input("หยิบสินค้าชิ้นที่ 5 :")
basket.append(Products5)
print("Products in basket ",basket)